declare module "tailwindcss/colors" {
  export const black: string;
  export const white: string;
  export const rose: any;
  export const pink: any;
  export const fuchsia: any;
  export const purple: any;
  export const violet: any;
  export const indigo: any;
  export const blue: any;
  export const lightBlue: any;
  export const cyan: any;
  export const teal: any;
  export const emerald: any;
  export const green: any;
  export const lime: any;
  export const yellow: any;
  export const amber: any;
  export const orange: any;
  export const red: any;
  export const warmGray: any;
  export const trueGray: any;
  export const gray: any;
  export const coolGray: any;
  export const blueGray: any;
}
